Potion_inventory:
create table
  public.potion_inventory (
    id bigint generated by default as identity,
    sku text null default ''::text,
    quantity integer null default 0,
    price integer null default 0,
    potion_type integer[] null,
    name text null,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

Global_inventory:
create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer null,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

Carts:
create table
  public.carts (
    id bigint generated by default as identity,
    customer_name text not null,
    payment text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

Cart_items:
create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id bigint null,
    quantity integer null,
    item_sku text null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id)
  ) tablespace pg_default;
